In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns

In [2]:
data = {
    "YearsExperience": [
        1.1, 1.3, 1.5, 2.0, 2.2,
        2.9, 3.0, 3.2, 3.7, 3.9,
        4.0, 4.5, 4.9, 5.1, 5.3,
        5.9, 6.0, 6.8, 7.1, 7.9,
        8.2, 8.7, 9.0, 9.5, 10.3
    ],

    "Salary": [
        39343, 46205, 37731, 43525, 39891,
        56642, 60150, 54445, 57189, 63218,
        55794, 61111, 67938, 66029, 83088,
        81363, 93940, 91738, 98273, 101302,
        113812, 109431, 105582, 116969, 122391
    ]
}

In [3]:
df = pd.DataFrame(data)

In [5]:
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [7]:
X=df[["YearsExperience"]]
y=df["Salary"]

In [8]:
y

0      39343
1      46205
2      37731
3      43525
4      39891
5      56642
6      60150
7      54445
8      57189
9      63218
10     55794
11     61111
12     67938
13     66029
14     83088
15     81363
16     93940
17     91738
18     98273
19    101302
20    113812
21    109431
22    105582
23    116969
24    122391
Name: Salary, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
X_train

    YearsExperience
9               3.9
13              5.1
1               1.3
22              9.0
5               2.9
2               1.5
12              4.9
15              5.9
3               2.0
4               2.2
20              8.2
17              6.8
21              8.7
18              7.1
24             10.3
7               3.2
10              4.0
14              5.3
19              7.9
6               3.0